### ISSUE TITLE
[EPIC] Allow attaching extra files to datasets

### ISSUE THREAD

**Issue by Ostrzyciel** [RiverBench/RiverBench#128]
I was asked about this already by a few people – would it be possible to attach for example SPARQL queries, RML files, or other resources to a dataset? This would open up the way to many many more new benchmark tasks.

This does make sense, but I don't want to make this an ad-hoc feature that will be hard to maintain. I think we should have a generic way of defining extra resource types, including them with datasets, and publishing them.

I'm thinking of two base resource types:

- "Small" – relatively small (<100KB) text files that we can embed on the website, besides also providing download links.
  - For example: SPARQL queries, RML files.
  - These would be uploaded to the dataset repo itself (in git).
- "Big" – any bigger file, or just any binary file. It would be only linked on the website and not processed in any way.
  - For example: source data for RML annotation.
  - These would be uploaded to the source release – just like the sources of the dataset itself.

TODO:

- [ ] Create a framework for defining extra resource types.
  - We need a curated list of resource types that we allow, for example: SPARQL query, RML template. This to make sure that the attached resources are annotated in a systematic and uniform manner.
  - These should most likely be defined in the `schema` repository, similar to the SHACL shapes library already there.
  - The resource type would define the media type, compression, packaging format, etc. This information (semantic, of course) will be later included with the dataset metadata.
  - The resource type should also define the pygments language name for syntax highlighting on the website, if it's a "small" resource.
- [ ] Link the extra resource types to the task and profile system.
  - Group all tasks requiring a given resource type in one category (for example: `category-flat-sparql`). 
  - Add SHACL shapes to the library to handle this.
- [ ] Extend the dataset description system to include the extra resources.
  - Include SHACL to validate if the descriptions make sense (i.e., if they refer to a valid extra resource type).
  - I guess the resources should be defined as blank nodes... They must be given IRIs, though, by the CI.
- [ ] Add automatic packaging and releasing for the extra resources.
  - "Small" resources:
    - Generate a doc page for each resource. Include there a download link, metadata information, and transclude the content of the file in a code block.
    - Copy the resource from the source repo to the docs (for transclusion) and to the release (for publishing).
  - "Big" resources:
    - Generate a doc page for the resource with its semantic metadata and download link.
    - Copy the resource from the source release to the actual release.
  - Generate an overview page listing all additional resources, grouped by resource type.
  - Include an admonition on the dataset page pointing users to the extra resource page. The admonition should include info on what resource types are supported by the dataset (e.g., "This dataset has SPARQL queries available" or sth like that).

**Comment by Ostrzyciel** [comment]
I'm not sure when I'll have the bandwidth for this task... for now I'm leaving it without a milestone.

If anyone is interested in this, let me know, maybe we can prioritize this.
