### ISSUE TITLE
Make the 2.0.1 release

### ISSUE THREAD

**Issue by Ostrzyciel** [RiverBench/RiverBench#90]
Before the release:

- [x] Check if the metadata added in #89 is consistent and the dump is complete.
- [x] Check if all tasks in the milestone are closed.

Release:

- [x] Make a stable release of all datasets due to #89 
- [x] Check if all datasets were released and updated in the doc repo, stable branch.
- [x] Make a stable release for each category.
- [x] Check if the categories were updated in the doc repo, stable branch.
- [x] Make a stable release in the main repo.

After the release:

- [x] Close this task and the milestone
- [x] Check if everything works (see #67)

**Comment by Ostrzyciel** [comment]
All done! :partying_face:
